import{a as H,S as O,i as c}from"./assets/vendor-b0d10f48.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const q="44413668-2012401924f35061b4cb3018c",M="https://pixabay.com/api";async function R(a,n,r){const{data:s}=await H.get(`${M}/?key=${q}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${r}&page=${n}`);return s}document.addEventListener("DOMContentLoaded",B);function B(){const a=document.getElementById("search-form"),n=document.querySelector(".gallery"),r=document.querySelector(".load-more");let s="",t=1;const o=40,i=new O(".gallery a",{captionsData:"alt"});r.style.display="none",a.addEventListener("submit",d),r.addEventListener("click",u);async function d(e){if(e.preventDefault(),n.innerHTML="",s=e.target.searchQuery.value.trim(),s.length<1){L("Search input must not be empty!"),e.target.searchQuery.value="",r.style.display="none";return}t=1,await u()}async function u(){try{const e=await R(s,t,o);p(e)}catch(e){g(e)}}function p(e){if(e.totalHits===0){r.style.display="none",f("Sorry, there are no images matching your search query. Please try again.");return}m(e.hits),t===1?w(`Hooray! We found ${e.totalHits} images.`):h(),b(e.totalHits),t+=1}function g(e){console.error(e),f("An error occurred while fetching images. Please try again later.")}function m(e){const l=e.map(y).join("");n.insertAdjacentHTML("beforeend",l),i.refresh()}function y({webformatURL:e,largeImageURL:l,tags:$,likes:S,views:E,comments:I,downloads:P}){return`
      <div class="photo-card">
          <a href="${l}">
              <img src="${e}" alt="${$}" loading="lazy" />
          </a>
          <div class="info">
              <p class="info-item"><b>Likes</b> ${S}</p>
              <p class="info-item"><b>Views</b> ${E}</p>
              <p class="info-item"><b>Comments</b> ${I}</p>
              <p class="info-item"><b>Downloads</b> ${P}</p>
          </div>
      </div>
    `}function h(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function b(e){t*o>=e?(r.style.display="none",v("We're sorry, but you've reached the end of search results.")):r.style.display="block"}function f(e){c.error({title:"Error",position:"topRight",message:e})}function w(e){c.success({title:"Success",position:"topRight",message:e})}function v(e){c.info({title:"Info",position:"topRight",message:e})}function L(e){c.warning({title:"Warning",position:"topRight",message:e})}}
//# sourceMappingURL=commonHelpers.js.map
