import{a as O,S as P,i as l}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const H="44413668-2012401924f35061b4cb3018c",M="Oops! Something went wrong! Try realoding the page!",q="https://pixabay.com/api";async function x(a,r,n){try{return(await O.get(`${q}/?key=${H}&q=${a}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${n}&page=${r}`)).data}catch{throw new Error(M)}}document.addEventListener("DOMContentLoaded",B);function B(){const a=document.getElementById("search-form"),r=document.querySelector(".gallery"),n=document.querySelector(".load-more");let s="",t=1;const o=40;n.style.display="none",a.addEventListener("submit",i),n.addEventListener("click",u);async function i(e){e.preventDefault(),r.innerHTML="",s=e.target.searchQuery.value.trim(),t=1,await u()}async function u(){try{const e=await x(s,t,o);d(e)}catch(e){p(e)}}function d(e){if(e.totalHits===0){f("Sorry, there are no images matching your search query. Please try again.");return}g(e.hits),t===1?w(`Hooray! We found ${e.totalHits} images.`):y(),t+=1,b(e.totalHits)}function p(e){console.error(e),f("An error occurred while fetching images. Please try again later.")}function g(e){const c=e.map(m).join("");r.insertAdjacentHTML("beforeend",c),h()}function m({webformatURL:e,largeImageURL:c,tags:v,likes:$,views:S,comments:E,downloads:I}){return`
      <div class="photo-card">
          <a href="${c}">
              <img src="${e}" alt="${v}" loading="lazy" />
          </a>
          <div class="info">
              <p class="info-item"><b>Likes</b> ${$}</p>
              <p class="info-item"><b>Views</b> ${S}</p>
              <p class="info-item"><b>Comments</b> ${E}</p>
              <p class="info-item"><b>Downloads</b> ${I}</p>
          </div>
      </div>
    `}function h(){new P(".gallery a",{captionDelay:250,captionsData:"alt"}).refresh()}function y(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function b(e){t*o>=e?(n.style.display="none",L("We're sorry, but you've reached the end of search results.")):n.style.display="block"}function f(e){l.error({title:"Error",position:"topRight",message:e})}function w(e){l.success({title:"Success",position:"topRight",message:e})}function L(e){l.info({title:"Info",position:"topRight",message:e})}}
//# sourceMappingURL=commonHelpers.js.map
